version: '3'

services:
  frontend:
    image: build2024/web:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://api:9000
      - FRONT_URL=http://localhost:3000
    networks:
      - mercari_network

  api:
    image: build2024/app:latest
    ports:
      - "9000:9000"
    environment:
      - FRONT_URL=http://frontend:3000
    networks:
      - mercari_network

networks:
  mercari_network:
    driver: bridge
