FROM node:20-alpine

ENV REACT_APP_API_URL=http://api:9000
ENV FRONT_URL=http://localhost:3000

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
